CREATE TABLE IF NOT EXISTS PRODUCT(
PRO_ID TEXT PRIMARY KEY,
PRO_NAME TEXT,
PRO_PRICE TEXT,
PRO_COM TEXT
);
INSERT INTO PRODUCT(PRO_ID,PRO_NAME,PRO_PRICE,PRO_COM) 
VALUES 
('101','MOTHER BOARD','3200','15'),
('102','KEY BOARD','450','16'),
('103','ZIP DRIVE','250','14'),
('104','SPEAKER','550','16'),
('105','MONITOR','5000','11'),
('106','DVD DRIVE','900','12'),
('107','CD DRIVE','800','12'),
('108','PRINTER','2600','13'),
('109','REFILL CARTRIDGE','350','13'),
('110','MOUSE','250','12');
SELECT PRO_NAME, PRO_PRICE
    FROM PRODUCT
    WHERE pro_price = (SELECT MIN(pro_price) FROM PRODUCT);
SELECT PRO_NAME, PRO_PRICE
    FROM PRODUCT
    WHERE PRO_PRICE = (SELECT MAX(PRO_PRICE) FROM PRODUCT);
SELECT *
FROM PRODUCT
WHERE PRO_COM = 12
AND PRO_PRICE > 500;

SELECT *
FROM PRODUCT
WHERE PRO_NAME LIKE '%R';

SELECT *
FROM PRODUCT
WHERE PRO_NAME LIKE '%O%';

SELECT *
FROM PRODUCT
WHERE PRO_NAME LIKE '_O%';

SELECT *
FROM PRODUCT
WHERE PRO_NAME LIKE '_____';

UPDATE PRODUCT
SET PRO_PRICE = 300
WHERE PRO_NAME = 'MOUSE';

UPDATE PRODUCT
SET PRO_NAME = 'WIRELESS KEYBOARD'
WHERE PRO_ID = 102;

DELETE FROM PRODUCT
WHERE PRO_PRICE < 300;

DELETE FROM PRODUCT
WHERE PRO_NAME LIKE '%DRIVE%';

SELECT * FROM PRODUCT;
