CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY_KEY,
    NAME TEXT NOT NULL,
    ADRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
    );

INSERT INTO STUDENT (ROLL_NO,NAME,ADRESS,PHONE,AGE) VALUES
('1','RAM','DEHLI','*****',18),
('2','RAMESH','GURGAON','*****',18),
('3','SUJIT','ROHTAK','*****',17),
('4','SURESH','DEHLI','*****',19),
('5','AYAAN','ROHTAK','*****',17),
('6','HARSH','GURGOAN','*****',20);

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE = 18 AND ADRESS = 'DEHLI';

SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM';

SELECT * FROM STUDENT WHERE NAME = 'RAM' OR NAME = 'SUJIT';

SELECT * FROM STUDENT WHERE NAME = 'RAM' OR AGE = 20;

SELECT * FROM STUDENT WHERE AGE = 18 AND (NAME ='RAM' OR NAME = 'RAMESH')